# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  imageRepository: 'sampritighosh060399/devops-learning-tracker'
  dockerfilePath: 'Dockerfile'
  tag: '$(Build.BuildId)'

steps:
- task: Docker@2
  displayName: Build and Push Docker Image
  inputs:
    containerRegistry: 'dockerhub-connection'
    repository: 'sampritighosh060399/devops-learning-tracker'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: |
      latest
      $(Build.BuildId)