"FROM nginx:alpine

COPY dist/devops-learning-tracker/browser /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"
# Stage 1: Build Angular App
FROM node:22 AS build

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build

# Stage 2: Nginx Server
FROM nginx:alpine

COPY --from=build /app/dist/devops-learning-tracker/browser /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g
