apiVersion: apps/v1
kind: Deployment

metadata:
  name: devops-learning-tracker

spec:
  replicas: 2

  selector:
    matchLabels:
      app: devops-learning-tracker

  template:
    metadata:
      labels:
        app: devops-learning-tracker

    spec:
      containers:
      - name: angular-app
        image: sampritighosh060399/devops-learning-tracker:v2
        ports:
        - containerPort: 80
